info:
  contact: { }
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
        - 首页
  /login/login:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
        - 登录
  /login/register:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
        - 注册
swagger: "2.0"
